### PR TITLE
Update open controls version, and tests appropriately

### PR DESCRIPTION
**Pull request by charmasaur**
Open controls 4.3.0 includes bug fixes for DDS generation, so that now
they always produce identities when pre_post_rotation is set.

### CODE REVIEW

**Review by leoadec — COMMENTED** [review]
Looks good, just curious to know if there's some advantage to using Open Controls 4.3.0 instead of 4.4.0

**Comment by charmasaur** [comment]
In general I think we should be as permissive as possible with our version requirements, to make everything as compatible as possible. In this case, while 4.4.0 does have a nice new feature and some bug fixes, those aren't actually particularly relevant to this repo (that is, if the user is happy to deal with 4.3.0 and its bugs, this repo is happy with it too). That's not true for <4.3.0, because for <4.3.0 this repo's tests fail.

**Review by leoadec — APPROVED** [review]
That is fair enough, and it also means that not everything depends on the HEAD of everything ;)

**Comment by charmasaur** [comment]
Haha, very true, you caught me in my web of lies!

But more seriously, IMO things are quite different between open and closed ecosystems. In a closed ecosystem, we can (technically) upgrade everything in sync, so having a single "company-wide HEAD" (i.e. everything depends on everything) is possible.

In an open ecosystem, some packages will upgrade before/after other packages, which means a single source-of-truth-HEAD-for-everything can't exist. Moreover, for a language like Python that doesn't support multiple versions of a package within the same runtime, compatibility of your package ends up being restricted by the compatibilities of all your dependencies. With those two unfortunate facts in mind, we're left in a world where we need to be good backwards-compatibility and versioning citizens (making changes backwards-compatible wherever possible, and using something like semver to clearly indicate when breaking changes have been made), and good dependency citizens (by being as compatible as we can).

**Pull request merged**
