### PR TITLE
misc: Update README about deprecation

### PR DESCRIPTION
**Pull request by tachikoma-li**
Addresses: https://qctrl.atlassian.net/browse/BLDR-771

The ticket suggests a final release before the deprecation.  I am not sure about whether it's necessary since there is no development for this package for a long time. Besides, after this repo is archived, it's still publically available, but in read-only mode, and people (if any) could still download it and use it. If they had issues with this package (for example, doesn't support the latest version of cirq), they might want to open an issue here and then notice it's deprecated.

I think we can update the README and then proceed to archive it directly, as suggested in the github  [doc](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories).
WDYT @abenseny  @Jacqueslee

### CODE REVIEW

**Comment by abenseny** [comment]
IIRC, this was brought up by Chris F that we might want to do a final release so a user downloading the publicly available latest version would see that this is deprecated and no longer maintained.

**Comment by tachikoma-li** [comment]
There is no development for this repo for a long time. Wondering do we need to do a final release (which would only be updating README) before archiving it? @cfarrend.

**Comment by cfarrend** [comment]
@tachikoma-li Up to you guys. There is also another discussion whether we keep the repository public when archiving it. Was a CoP item but I haven't been able to attend yet.

**Comment by tachikoma-li** [comment]
> @tachikoma-li Up to you guys. There is also another discussion whether we keep the repository public when archiving it. Was a CoP item but I haven't been able to attend yet.

We'll archive this repo without the extra release. The last CoP was postponed as many leaders were in another meeting. I guess we can discuss whether to keep the archived repo public later. @cfarrend

**Review by leoadec — APPROVED** [review]

**Pull request merged**
